### ISSUE TITLE
[MacOS] Warning "Not installed" even though the addon is installed and activated

### ISSUE THREAD

**Issue by CamilleHbp** [Stremio/stremio-local-addon#41]
I'm using stremio on a Macbook Pro Silicon, MacOS 13.1, fresh install of stremio. I get a "Not installed" warning, even though the addon is installed and activated. I can't add a single file to the library, it says added and then nothing happens. And if I switch to another tab, go back to `Discover` and click on others, I can't see the `Local Files` submenu.

<img width="1378" alt="Screenshot 2023-02-13 at 20 43 27" src="https://user-images.githubusercontent.com/11173924/218560310-31142675-6d8c-4a52-bbd5-1aafe49f24c1.png">

As you can see the addon is downloaded and activated. I've already restarted the app numerous times.

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/11173924/218559916-0c19febe-e832-40f3-bb63-0b21a2739ef4.png">

<img width="1381" alt="Screenshot 2023-02-13 at 20 46 13" src="https://user-images.githubusercontent.com/11173924/218559186-e8464ccd-6e3c-48c1-88c9-92d8e312c1ec.png">

I don't know what other information I can give you. Any help? Thanks :)

**Comment by TRtomasz** [comment]
should be fixed now

**Comment by CamilleHbp** [comment]
The local add-on completely fails on my mac. Definitely not fixed on my side.

Navigating to `Discover -> Other -> Local Files` gives me this error.

<img width="1725" alt="image" src="https://github.com/Stremio/stremio-local-addon/assets/11173924/2baea965-e590-4f17-848d-f6f5274d3466">
